# Generated by Django 4.2 on 2024-08-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('quantity_sold', models.IntegerField()),
                ('rating', models.FloatField()),
                ('review_count', models.IntegerField()),
            ],
        ),
    ]
